//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace eFlowApi.Module.BusinessObjects.eFlowModel
{

    public partial class Employee : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fID;
        [Indexed(Unique = true)]
        public string ID
        {
            get { return fID; }
            set { SetPropertyValue<string>(nameof(ID), ref fID, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        Department fDepartment;
        [Association(@"UserReferencesDepartment")]
        public Department Department
        {
            get { return fDepartment; }
            set { SetPropertyValue<Department>(nameof(Department), ref fDepartment, value); }
        }
        JobTitle fJobTitle;
        public JobTitle JobTitle
        {
            get { return fJobTitle; }
            set { SetPropertyValue<JobTitle>(nameof(JobTitle), ref fJobTitle, value); }
        }
        bool fIsEnabled;
        public bool IsEnabled
        {
            get { return fIsEnabled; }
            set { SetPropertyValue<bool>(nameof(IsEnabled), ref fIsEnabled, value); }
        }
        string fPassword;
        public string Password
        {
            get { return fPassword; }
            set { SetPropertyValue<string>(nameof(Password), ref fPassword, value); }
        }
        string fEmail;
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        byte[] fSignStamp;
        [MemberDesignTimeVisibility(true)]
        public byte[] SignStamp
        {
            get { return fSignStamp; }
            set { SetPropertyValue<byte[]>(nameof(SignStamp), ref fSignStamp, value); }
        }
        string fNote;
        [Size(SizeAttribute.Unlimited)]
        public string Note
        {
            get { return fNote; }
            set { SetPropertyValue<string>(nameof(Note), ref fNote, value); }
        }
        [Association(@"JobRoleReferencesUser")]
        public XPCollection<JobRole> JobRoles { get { return GetCollection<JobRole>(nameof(JobRoles)); } }
        [Association(@"SignAgentReferencesUser")]
        public XPCollection<SignAgent> SignAgents { get { return GetCollection<SignAgent>(nameof(SignAgents)); } }
    }

}
