//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace eFlowApi.Module.BusinessObjects.eFlowModel
{

    public partial class FormType : DevExpress.Persistent.BaseImpl.BaseObject
    {
        DateTime fName;
        [Indexed(Unique = true)]
        public DateTime Name
        {
            get { return fName; }
            set { SetPropertyValue<DateTime>(nameof(Name), ref fName, value); }
        }
        string fNumberPrefix;
        public string NumberPrefix
        {
            get { return fNumberPrefix; }
            set { SetPropertyValue<string>(nameof(NumberPrefix), ref fNumberPrefix, value); }
        }
        string fNote;
        [Size(SizeAttribute.Unlimited)]
        public string Note
        {
            get { return fNote; }
            set { SetPropertyValue<string>(nameof(Note), ref fNote, value); }
        }
    }

}
