//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace eFlowApi.Module.BusinessObjects.eFlowModel
{

    [NonPersistent]
    public partial class FormBase : XPCustomObject
    {
        string fFormNumber;
        [Key]
        public string FormNumber
        {
            get { return fFormNumber; }
            set { SetPropertyValue<string>(nameof(FormNumber), ref fFormNumber, value); }
        }
        DateTime fFormDate;
        public DateTime FormDate
        {
            get { return fFormDate; }
            set { SetPropertyValue<DateTime>(nameof(FormDate), ref fFormDate, value); }
        }
        FormStatus fFormStatus;
        public FormStatus FormStatus
        {
            get { return fFormStatus; }
            set { SetPropertyValue<FormStatus>(nameof(FormStatus), ref fFormStatus, value); }
        }
        Employee fMaker;
        public Employee Maker
        {
            get { return fMaker; }
            set { SetPropertyValue<Employee>(nameof(Maker), ref fMaker, value); }
        }
        DateTime fCreateTime;
        public DateTime CreateTime
        {
            get { return fCreateTime; }
            set { SetPropertyValue<DateTime>(nameof(CreateTime), ref fCreateTime, value); }
        }
        DateTime fApprovedTime;
        public DateTime ApprovedTime
        {
            get { return fApprovedTime; }
            set { SetPropertyValue<DateTime>(nameof(ApprovedTime), ref fApprovedTime, value); }
        }
        string fSubject;
        public string Subject
        {
            get { return fSubject; }
            set { SetPropertyValue<string>(nameof(Subject), ref fSubject, value); }
        }
        string fCurrentSignOrder;
        public string CurrentSignOrder
        {
            get { return fCurrentSignOrder; }
            set { SetPropertyValue<string>(nameof(CurrentSignOrder), ref fCurrentSignOrder, value); }
        }
        string fCurrentSigner;
        public string CurrentSigner
        {
            get { return fCurrentSigner; }
            set { SetPropertyValue<string>(nameof(CurrentSigner), ref fCurrentSigner, value); }
        }
    }

}
