//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace eFlowApi.Module.BusinessObjects.eFlowModel
{

    public partial class SignAgentForm : DevExpress.Persistent.BaseImpl.BaseObject
    {
        SignAgent fSignAgent;
        [Association(@"SignAgentFormReferencesSignAgent")]
        public SignAgent SignAgent
        {
            get { return fSignAgent; }
            set { SetPropertyValue<SignAgent>(nameof(SignAgent), ref fSignAgent, value); }
        }
        FormType fForm;
        public FormType Form
        {
            get { return fForm; }
            set { SetPropertyValue<FormType>(nameof(Form), ref fForm, value); }
        }
    }

}
