//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace eFlowApi.Module.BusinessObjects.eFlowModel
{

    public partial class SignStep : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fFormNumber;
        public string FormNumber
        {
            get { return fFormNumber; }
            set { SetPropertyValue<string>(nameof(FormNumber), ref fFormNumber, value); }
        }
        string fSignOrder;
        public string SignOrder
        {
            get { return fSignOrder; }
            set { SetPropertyValue<string>(nameof(SignOrder), ref fSignOrder, value); }
        }
        Employee fSigner;
        public Employee Signer
        {
            get { return fSigner; }
            set { SetPropertyValue<Employee>(nameof(Signer), ref fSigner, value); }
        }
        Employee fRealSigner;
        public Employee RealSigner
        {
            get { return fRealSigner; }
            set { SetPropertyValue<Employee>(nameof(RealSigner), ref fRealSigner, value); }
        }
        SignResult fResult;
        public SignResult Result
        {
            get { return fResult; }
            set { SetPropertyValue<SignResult>(nameof(Result), ref fResult, value); }
        }
        string fSignTime;
        public string SignTime
        {
            get { return fSignTime; }
            set { SetPropertyValue<string>(nameof(SignTime), ref fSignTime, value); }
        }
        string fComment;
        [Size(SizeAttribute.Unlimited)]
        public string Comment
        {
            get { return fComment; }
            set { SetPropertyValue<string>(nameof(Comment), ref fComment, value); }
        }
        [Association(@"SignStepAttachmentReferencesFormSignStep")]
        public XPCollection<SignStepAttachment> SignStepAttachments { get { return GetCollection<SignStepAttachment>(nameof(SignStepAttachments)); } }
    }

}
