//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace eFlowApi.Module.BusinessObjects.eFlowModel
{

    public partial class SignAgent : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Employee fUser;
        [Association(@"SignAgentReferencesUser")]
        public Employee User
        {
            get { return fUser; }
            set { SetPropertyValue<Employee>(nameof(User), ref fUser, value); }
        }
        Employee fAgent;
        public Employee Agent
        {
            get { return fAgent; }
            set { SetPropertyValue<Employee>(nameof(Agent), ref fAgent, value); }
        }
        string fStartTime;
        public string StartTime
        {
            get { return fStartTime; }
            set { SetPropertyValue<string>(nameof(StartTime), ref fStartTime, value); }
        }
        string fEndTime;
        public string EndTime
        {
            get { return fEndTime; }
            set { SetPropertyValue<string>(nameof(EndTime), ref fEndTime, value); }
        }
        [Association(@"SignAgentFormReferencesSignAgent")]
        public XPCollection<SignAgentForm> SignAgentForms { get { return GetCollection<SignAgentForm>(nameof(SignAgentForms)); } }
    }

}
